<?xml version="1.0"?>
<package format="2">
  <name>eklt_rebuild</name>
  <version>0.1.0</version>
  <description>Event-based KLT tracking with optional event-only reconstruction.</description>

  <maintainer email="petercalifano.gs@gmail.com">Pietro Califano</maintainer>
  <maintainer email="daniel.gehrig18@gmail.com">Daniel Gehrig</maintainer>

  <license>GPL-3.0-only</license>

  <buildtool_depend>catkin</buildtool_depend>
  <buildtool_depend>catkin_simple</buildtool_depend>
  
  <depend>ceres_catkin</depend>
  <depend>eigen_catkin</depend>
 
  <depend>sensor_msgs</depend>
  <depend>roscpp</depend>
  <depend>glog_catkin</depend>
  <depend>gflags_catkin</depend>
  <depend>dvs_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>image_geometry</depend>

</package>
