function bPassed = RunEkltRebuildRegression(charCaseName, charToolboxPath, charMexPath)
%% SIGNATURE
% bPassed = RunEkltRebuildRegression(charCaseName, charToolboxPath, charMexPath)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Exercise one isolated EKLT MATLAB wrapper regression through generated
% classes and the R2024b MEX module.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% charCaseName       Regression case to execute.
% charToolboxPath    Build-tree directory containing generated MATLAB classes.
% charMexPath        Build-tree directory containing the generated MEX module.
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% bPassed            True after the selected regression completes.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 28-07-2026  Pietro Califano     First prototype.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% wrap_adapters.CFibarReconstructorAdapter generated by gtwrap.
% -------------------------------------------------------------------------------------------------------------

arguments (Input)
    charCaseName (1, :) char
    charToolboxPath (1, :) char
    charMexPath (1, :) char
end

arguments (Output)
    bPassed (1, 1) logical
end

% Load only the two generated build-tree surfaces required by the wrapper.
addpath(charToolboxPath);
addpath(charMexPath);

charMatlabRelease = version('-release');
assert(strcmp(charMatlabRelease, '2024b'), ...
       'RunEkltRebuildRegression:WrongRelease', ...
       'Expected MATLAB R2024b, found %s.', charMatlabRelease);
assert(exist('eklt_rebuild_wrapper', 'file') == 3, ...
       'RunEkltRebuildRegression:MissingMex', ...
       'The eklt_rebuild MEX module is unavailable.');
assert(exist('wrap_adapters.CFibarReconstructorAdapter', 'class') == 8, ...
       'RunEkltRebuildRegression:MissingClass', ...
       'The generated FIBAR adapter class is unavailable.');

switch charCaseName
    case 'reconstruction'
        % Verify Eigen-backed vectors, owning image storage, and patch metadata
        % through the complete generated boundary.
        objReconstructor = wrap_adapters.CFibarReconstructorAdapter( ...
            6, 5, uint32(10000), 0.5, false);
        dX = [2.0; 3.0; 2.0; 3.0];
        dY = [2.0; 2.0; 3.0; 3.0];
        dPolarity = [1.0; -1.0; 1.0; -1.0];
        dTimestampsUs = [10.0; 20.0; 30.0; 40.0];

        objReconstructor.acceptEvents(dX, dY, dPolarity, dTimestampsUs);
        dImage = objReconstructor.requestImage(int64(40));
        objPatch = objReconstructor.requestPatch(2, 2, 1, int64(40));
        dPatchIntensity = objPatch.intensity();
        dPatchValidMask = objPatch.validMask();

        assert(isequal(size(dImage), [5, 6]));
        assert(all(isfinite(dImage), 'all'));
        assert(isequal(size(dPatchIntensity), [3, 3]));
        assert(isequal(size(dPatchValidMask), [3, 3]));
        assert(all(isfinite(dPatchIntensity), 'all'));
        assert(objPatch.validFraction() >= 0.0);
        assert(objPatch.validFraction() <= 1.0);

    case 'invalid_batch_recovery'
        % Prove that complete conversion precedes native mutation and that a
        % caught generated-boundary error leaves the MEX module callable.
        objReconstructor = wrap_adapters.CFibarReconstructorAdapter( ...
            6, 5, uint32(10000), 0.5, false);
        objReconstructor.acceptEvent(uint16(2), uint16(2), int8(1), int64(40));

        bCaughtExpectedError = false;
        try
            objReconstructor.acceptEvents( ...
                [2.0; 3.5], [2.0; 3.0], [1.0; -1.0], [50.0; 60.0]);
        catch objException
            bCaughtExpectedError = true;
            assert(~isempty(objException.message));
        end
        assert(bCaughtExpectedError);
        assert(objReconstructor.latestTimestampUs() == int64(40));

        objReconstructor.acceptEvents( ...
            [2.0; 3.0], [2.0; 3.0], [1.0; -1.0], [50.0; 60.0]);
        dImageAfterRecovery = objReconstructor.requestImage(int64(60));
        assert(isequal(size(dImageAfterRecovery), [5, 6]));
        assert(all(isfinite(dImageAfterRecovery), 'all'));

    case 'reset_reuse'
        % Reset the native stream origin, then reuse the same generated object
        % with a later independent event sequence.
        objReconstructor = wrap_adapters.CFibarReconstructorAdapter( ...
            6, 5, uint32(10000), 0.5, false);
        objReconstructor.acceptEvents( ...
            [2.0; 3.0], [2.0; 3.0], [1.0; -1.0], [10.0; 20.0]);
        assert(objReconstructor.latestTimestampUs() == int64(20));

        objReconstructor.reset();
        assert(objReconstructor.latestTimestampUs() == int64(-1));
        objReconstructor.acceptEvents( ...
            [2.0; 3.0], [2.0; 3.0], [-1.0; 1.0], [100.0; 110.0]);
        dImageAfterReset = objReconstructor.requestImage(int64(110));
        assert(isequal(size(dImageAfterReset), [5, 6]));
        assert(all(isfinite(dImageAfterReset), 'all'));

    case 'clear_lifecycle'
        % Isolate the destructive clear commands in the base workspace so
        % teardown does not erase this regression function's own arguments.
        evalin('base', ...
               ['objReconstructor = wrap_adapters.CFibarReconstructorAdapter(', ...
                '6, 5, uint32(10000), 0.5, false); ', ...
                'clear objReconstructor; clear classes; clear mex;']);

    otherwise
        error('RunEkltRebuildRegression:UnknownCase', ...
              'Unknown MATLAB wrapper regression case: %s', charCaseName);
end

bPassed = true;
fprintf('EKLT_MATLAB_%s_OK release=%s\n', upper(charCaseName), charMatlabRelease);

end
